import shutil
from pathlib import Path
import yaml


class Initializer:
    """
    Utility class for setting up the directory structure required to run
    SFINCS model simulations, and for writing a case-scoped HydroMT
    ``data_catalog.yml``.

    Unlike XBeach/SWAN, SFINCS has no single text template to stamp with
    placeholders: HydroMT-SFINCS writes the native ``sfincs.*`` files
    directly when the model is built (see ``preprocess.prepare_case``).
    ``Initializer`` is therefore scoped to two things: the folder layout,
    and a ``data_catalog.yml`` that always resolves against this case's own
    ``input/`` folder.

    The directory layout produced by this class is:

    .. code-block:: text

        root_path/
        ├── input/
        │   ├── data_catalog.yml   ← generated by write_data_catalog()
        │   └── ...                ← place your static input files here before running
        ├── pros/
        ├── run/
        └── output/

    Parameters
    ----------
    root_path : str
        Root directory of the case. All sub-folders are created inside this
        path. Works with or without a trailing slash.
    """

    def __init__(self, root_path):
        self.root_path = root_path
        self.folder_names = ['input', 'pros', 'run', 'output']
        self.dict_folders = {
            name: f'{Path(self.root_path) / name}/' for name in self.folder_names
        }
        print('*** Initializing SFINCS model ***\n')

    def create_folders(self):
        """
        Create the full project folder structure.

        Creates the four standard sub-directories under ``root_path``:
        ``input/``, ``pros/``, ``run/``, and ``output/``. On a re-run,
        ``run/`` and ``output/`` are wiped with ``shutil.rmtree`` before being
        recreated so that stale files from a previous execution do not
        pollute the new case. ``input/`` and ``pros/`` are always left
        untouched.

        All directories are created with ``Path.mkdir(parents=True,
        exist_ok=True)``, so missing intermediate paths are handled
        automatically.
        """
        print('\n\t*** Creating project folder structure ***\n')

        for folder_name in self.folder_names:
            folder_path = Path(self.dict_folders[folder_name])
            if folder_name in ['output', 'run'] and folder_path.exists():
                shutil.rmtree(folder_path)
            folder_path.mkdir(parents=True, exist_ok=True)

    def write_data_catalog(self, datasets, filename='data_catalog.yml'):
        """
        Write a HydroMT ``data_catalog.yml`` scoped to this case's own
        ``input/`` folder.

        HydroMT resolves a relative ``path`` in a data catalog entry against
        the directory that contains the catalog file itself (unless a
        ``root`` is set in the catalog's meta section). Passing a bare
        filename (no directory separators) as ``path`` in *datasets*
        therefore always resolves to ``<this case>/input/<filename>`` -
        every case gets a self-contained catalog instead of one hardcoding
        an absolute path into another case's folder.

        Parameters
        ----------
        datasets : dict
            Mapping of dataset name to a HydroMT catalog entry, e.g.::

                {
                    "topobathy": {
                        "data_type": "RasterDataset",
                        "driver": "raster",
                        "path": "new_topobathy_SAI_1m_n.tif",
                        "crs": 32617,
                        "nodata": -3.4028235e+38,
                    }
                }

        filename : str, optional
            Name of the catalog file to write inside ``input/`` (default
            ``"data_catalog.yml"``).

        Returns
        -------
        str
            Path to the written ``data_catalog.yml``.
        """
        out_path = Path(self.dict_folders['input']) / filename
        with open(out_path, 'w') as f:
            yaml.safe_dump(datasets, f, sort_keys=False)

        return str(out_path)
